apiVersion: v1
kind: Pod
metadata:
  name: re-app-pod
  labels:
    name: resutl-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80


